### ISSUE TITLE
Fix HTTPS

### ISSUE THREAD

**Issue by fulldecent** [tomhschmidt/erc721-website#30]
# Work plan

- [ ] Remove CNAME from project root AND docs/ folders (THIS WILL BRING THE WEBSITE DOWN)
- [ ] Confirm website is down
- [ ] Wait 20 minutes
- [ ] Put back the CNAME file into docs/ folder only
- [ ] Wait 20 minutes
- [ ] Confirm website is up
- [ ] Confirm https://erc721.org works

Source: https://help.github.com/articles/troubleshooting-custom-domains/#https-errors

**Comment by brannondorsey** [comment]
+1. The current certificate is valid only for *.github.com, github.com, *.github.io, and github.io.
